### ISSUE TITLE
Documentation Checklist

### ISSUE THREAD

**Issue by TGRCdev** [TGRCdev/BigRock#1]
- [ ] Classes all have (sufficient) descriptions
- [ ] Documentation Website
- [ ] Building from source
    - [ ] Scons flags and options
    - [ ] Performance considerations
- [ ] Basic usage in plain C++
- [ ] Writing a custom wrapper
- [ ] Additional notes
    - Compiling with MinGW
        - MinGW compilation is mostly for compile-time error checking. MSVC is recommended for compatibility.
        - 64-bit compilation with MinGW requires `mingw-w64` on the PATH
        - Compiling with MinGW with `target=debug` does not statically link required libraries by default. If you are testing a debug build and it errors about needing something like `libgcc_s_seh.dll`, make sure your `mingw-w64` installation is on the `PATH`, or set `static_link_deps=yes`.
