### ISSUE TITLE
Misc Checklist

### ISSUE THREAD

**Issue by TGRCdev** [TGRCdev/BigRock#2]
- [ ] NEW NAME. BigRock is currently an active company that provides web services.
- [ ] Website
- [ ] Deploy location
- [ ] Performance graphs with various computer setups
- [ ] Re-establish MinGW compatibility
