### ISSUE TITLE
Library Checklist

### ISSUE THREAD

**Issue by TGRCdev** [TGRCdev/BigRock#3]
- [ ] Sealed geometry
- [ ] Stitching between different resolution cells
- [ ] Caching edge/plane triangle data
- [ ] Chunked terrain
- [ ] Custom tool for stuff like noise sampling
- [ ] As much multithreading/OpenCL/CUDA as humanly possible
- [ ] Vertex normals, texture coordinates
- [ ] Determine if there is a significant need for C++98/C++03 compliance instead of C++11
- [ ] Determine if there is a significant need for a C wrapper
